const ROWS=224,COLS=250;
const canvas=document.getElementById('heat'),ctx=canvas.getContext('2d');
const loading=document.getElementById('loading'),hover=document.getElementById('hover'),metricSel=document.getElementById('metric'),viewSel=document.getElementById('view'),statusEl=document.getElementById('status');
let meta,innerMeta,currentKey='r_per_trade',values=null,cdf=null;
const cache=new Map();
const pointsThresholds=[150,175,200,225,250,275,300];
const atrThresholds=[20,25,30,35,40,45,50];
const groups=[{s:0,e:30,n:'Fixed · 1 trade',mode:0,trades:1},{s:30,e:60,n:'Fixed · 2 trades',mode:0,trades:2},{s:60,e:65,n:'Trail · 1 trade',mode:1,trades:1},{s:65,e:70,n:'Trail · 2 trades',mode:1,trades:2},{s:70,e:160,n:'Mixed · 1 trade',mode:2,trades:1},{s:160,e:250,n:'Mixed · 2 trades',mode:2,trades:2}];
function mix(a,b,t){return a.map((v,i)=>Math.round(v+(b[i]-v)*t));}
function rgb(q){let t=q/255;if(t<.5)return mix([171,43,54],[58,67,79],t*2);return mix([58,67,79],[32,151,86],(t-.5)*2);}
function fmt(v,d){return Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});}
async function decodeMetric(key){if(cache.has(key))return cache.get(key);const txt=(await fetch(`data/${key}.b64`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text();})).trim();const bin=atob(txt),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));if(typeof DecompressionStream==='undefined')throw new Error('This browser does not support DecompressionStream.');const ds=new DecompressionStream('deflate');const ab=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer();const arr=new Uint8Array(ab);if(arr.length!==ROWS*COLS)throw new Error(`Expected ${ROWS*COLS} cells, got ${arr.length}`);cache.set(key,arr);return arr;}
function buildCdf(arr){const h=new Uint32Array(256);for(const q of arr)h[q]++;const out=new Uint8Array(256);let sum=0;for(let i=0;i<256;i++){sum+=h[i];out[i]=Math.round(255*sum/arr.length);}return out;}
async function setMetric(key){currentKey=key;loading.style.display='flex';loading.textContent='Loading real 56k landscape…';try{values=await decodeMetric(key);cdf=buildCdf(values);loading.style.display='none';statusEl.textContent=`${meta[key].label} loaded · 56,000 tested configurations`;draw();}catch(e){loading.style.display='flex';loading.textContent='Could not load heatmap data: '+e.message;}}
function size(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));draw();}
function displayQ(q){const m=meta[currentKey];let z=viewSel.value==='pct'?cdf[q]:q;if(m.invert)z=255-z;return z;}
function draw(){if(!values||!meta)return;const off=document.createElement('canvas');off.width=COLS;off.height=ROWS;const o=off.getContext('2d'),im=o.createImageData(COLS,ROWS);for(let i=0;i<values.length;i++){const c=rgb(displayQ(values[i])),p=i*4;im.data[p]=c[0];im.data[p+1]=c[1];im.data[p+2]=c[2];im.data[p+3]=255;}o.putImageData(im,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(off,0,0,canvas.width,canvas.height);const sx=canvas.width/COLS,sy=canvas.height/ROWS,d=devicePixelRatio||1;ctx.save();for(let r=16;r<ROWS;r+=16){if(r===112)continue;ctx.beginPath();ctx.moveTo(0,r*sy);ctx.lineTo(canvas.width,r*sy);ctx.strokeStyle='rgba(190,200,211,.42)';ctx.lineWidth=1*d;ctx.setLineDash([4*d,5*d]);ctx.stroke();}ctx.beginPath();ctx.moveTo(0,112*sy);ctx.lineTo(canvas.width,112*sy);ctx.strokeStyle='rgba(244,247,250,.92)';ctx.lineWidth=3*d;ctx.setLineDash([]);ctx.stroke();for(const x of [30,60,65,70,160]){ctx.beginPath();ctx.moveTo(x*sx,0);ctx.lineTo(x*sx,canvas.height);const hard=[60,70].includes(x);ctx.strokeStyle=hard?'rgba(244,247,250,.92)':'rgba(190,200,211,.52)';ctx.lineWidth=(hard?3:1)*d;ctx.setLineDash(hard?[]:[4*d,5*d]);ctx.stroke();}ctx.restore();}
function outerInfo(row){const isAtr=row>=112,local=row%112,t=Math.floor(local/16),w=local%16;return{mode:isAtr?'ATR':'Points',threshold:isAtr?`${atrThresholds[t]}% ATR`:`${pointsThresholds[t]} pts`,beyond:Math.floor(w/8),pm:Math.floor((w%8)/2),entry:w%2};}
function rawApprox(q){const m=meta[currentKey];return m.lo+(m.hi-m.lo)*(q/255);}
canvas.addEventListener('mousemove',e=>{if(!values)return;const r=canvas.getBoundingClientRect(),col=Math.max(0,Math.min(COLS-1,Math.floor((e.clientX-r.left)/r.width*COLS))),row=Math.max(0,Math.min(ROWS-1,Math.floor((e.clientY-r.top)/r.height*ROWS))),idx=row*COLS+col,q=values[idx],m=meta[currentKey],o=outerInfo(row),orig=meta.__order__[col],im=innerMeta[String(orig)],g=groups.find(x=>col>=x.s&&col<x.e),v=rawApprox(q),pct=Math.round(cdf[q]/255*100);hover.innerHTML=`<span>Outer: <b>${row+1} / 224</b></span><span>Inner: <b>${orig+1} / 250</b></span><span>Metric: <b>${m.label}</b></span><span>Range mode: <b>${o.mode}</b></span><span>Management: <b>${g?.n??'—'}</b></span><span>Max trades: <b>${im.maximum_trades_per_day}</b></span><span>Threshold: <b>${o.threshold}</b></span><span>Stop %: <b>${im.stop_london_range_percent}%</b></span><span>Value: <b>${fmt(v,m.decimals)}${viewSel.value==='pct'?` · P${pct}`:''}</b></span>`;});
metricSel.addEventListener('change',()=>setMetric(metricSel.value));
viewSel.addEventListener('change',draw);addEventListener('resize',size);
(async function init(){try{meta=await fetch('metrics.json',{cache:'no-store'}).then(r=>r.json());innerMeta=await fetch('inner_meta.json',{cache:'no-store'}).then(r=>r.json());for(const [k,m] of Object.entries(meta)){if(k.startsWith('__'))continue;const opt=document.createElement('option');opt.value=k;opt.textContent=m.label;metricSel.appendChild(opt);}metricSel.value=currentKey;size();await setMetric(currentKey);}catch(e){loading.textContent='Could not initialize interface: '+e.message;}})();
