'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const root=path.join(__dirname,'..');
const staging=fs.readFileSync(path.join(root,'staging-v1.html'),'utf8');
const viewer=fs.readFileSync(path.join(root,'region-analyzer-viewer-v001.js'),'utf8');
const bridge=fs.readFileSync(path.join(root,'session-package-bridge-v001.js'),'utf8');
assert.doesNotThrow(()=>new Function(viewer),'viewer must parse as JavaScript');

assert.match(staging,/region-analyzer-viewer-v001\.js\?v=017/,'staging must load the Region Analyzer viewer');
assert.match(staging,/RA v017/,'staging must expose the Region Analyzer build version');
assert.match(viewer,/region-analyzer\/catalog\.json/,'viewer must use the static Region Analyzer catalog');
for(const forbidden of ['computeStructuralRobustness','computeFacetReplication','ensureTopology','runScan(']){
  assert.ok(!viewer.includes(forbidden),`viewer must not invoke research recomputation: ${forbidden}`);
}
assert.match(bridge,/regionAnalyzerIdentity/,'package bridge must expose Region Analyzer package identity');
assert.match(bridge,/packageSha256/,'package bridge must expose exact package SHA-256');
assert.match(bridge,/descriptorSha256/,'package bridge must expose exact descriptor SHA-256');
assert.match(viewer,/physicalIndexByVisual/,'viewer must use the exact canonical physical-index map');
assert.match(viewer,/function exactPhysicalMap\(cur,src\)/,'viewer must derive visible mask indices from the canonical source map');
assert.match(viewer,/Canonical physical-index map is not a permutation/,'viewer must reject invalid canonical physical maps');
assert.match(viewer,/Visible cell is outside the canonical package/,'filtered cells must bind exactly to canonical source coordinates');
assert.match(viewer,/snap\?\.sourceSurface/,'viewer must verify masks against the canonical source surface when the visible surface is filtered');
assert.match(viewer,/const RUNG_HUES=\[220,190,145,36,334\]/,'Region Analyzer must use an ordered P-rung hue progression');
assert.match(viewer,/function rungColor\(id,r\)/,'viewer must derive color from rung first and region identity second');
assert.match(viewer,/sort\(\(a,b\)=>a\.p-b\.p\|\|String\(b\.id\)\.localeCompare\(String\(a\.id\)\)\)/,'overlapping masks must composite by P rung, with highest P winning and stable same-rung tie-break');
assert.match(viewer,/im\.data\[px\+3\]=156/,'region fill opacity must be uniform and clearly visible');
assert.doesNotMatch(viewer,/bound\?235:78|left=c\?lab\[i-1\]|right=c<cur\.cols-1\?lab\[i\+1\]/,'Region Analyzer must not add boundary or edge emphasis');
assert.match(viewer,/Object\.entries\(m\?\.region_dictionary\|\|\{\}\)\.map\(\(\[id,r\]\)=>\[id,rungColor\(id,r\)\]\)/,'viewer must freeze rung-aware colors by region identity');
assert.match(viewer,/function regionColor\(id\)\{return regionColors\.get\(id\)\|\|rungColor\(id,manifest\?\.region_dictionary\?\.\[id\]\);\}/,'region color lookup must use the fixed rung-aware table');
assert.match(viewer,/function stage6Mode\(role=mode6\)/,'Stage 6 must resolve the selected Mode and Tolerance population');
assert.match(viewer,/s\?\.tolerances\?\.\[tolerance\]/,'Stage 6 must bind candidate population to the selected tolerance');
assert.match(viewer,/function weightRun\(role=mode6\)/,'Stage 6 must resolve the selected stored v004 weighting run');
assert.match(viewer,/function ranked\(role=mode6,topOnly=true\)/,'Stage 6 must support full ranking and top-three ranking from the same stored run');
assert.match(viewer,/id="raMode"/,'Stage 6 menu must expose Performance and Stability modes');
assert.match(viewer,/id="raTolerance"/,'Stage 6 menu must expose the tolerance selector');
assert.match(viewer,/\[\['strict','Low'\],\['center','Mid'\],\['loose','High'\]\]/,'Tolerance must map Low\/Mid\/High to strict\/center\/loose stopping grids');
assert.match(viewer,/\[\['all','All'\],\['top','Top 3'\]\]/,'Stage 6 menu must expose All and Top 3 views');
assert.match(viewer,/function weightLabel\(run\)/,'weight selector must format stored Performance/Stability weights for humans');
assert.match(viewer,/'P '\+p\+'% \/ S '\+s\+'%'/,'weight selector must display P x% / S y% labels');
assert.doesNotMatch(viewer,/· Center/,'weight selector must not label the middle preset as Center');
assert.match(viewer,/runs\.map\(x=>'<option value="'\+esc\(\/CENTER\/i\.test\(x\.weight_id\)\?'center':x\.weight_id\)/,'weight selector must preserve stored run order while keeping the middle preset as the internal default');
assert.match(viewer,/kind!==\'ALL_PHYSICAL_CELLS\'&&kind!==\'BUNDLE_BITSET\'/,'viewer must accept frozen bundle-backed cleaned domains');
assert.match(viewer,/function verifyDomainBundle\(m,b\)/,'viewer must verify stored cleaned-domain bitsets after bundle load');
assert.match(viewer,/cleaned-domain mask popcount mismatch/,'viewer must reject a corrupted cleaned-domain bitset');
assert.match(viewer,/regionNumbers=new Map/,'Region Analyzer must keep stable numeric region identities separate from rank');
assert.match(viewer,/membership_hash\|\|a\[0\]/,'numeric region identity must derive from immutable membership order, not display order');
assert.match(viewer,/id=\"raSort\"/,'Stage 6 must expose a sort selector');
assert.match(viewer,/\[\['rank','Rank'\],\['id','ID'\],\['size','Size'\],\['p','P score'\],\['s','S score'\],\['score','6C score'\]\]/,'Stage 6 sort options must cover rank, identity, size, and all three scores');
assert.match(viewer,/title=\"Performance score\"/,'Stage 6 rows must expose Performance score separately');
assert.match(viewer,/title=\"Stability score\"/,'Stage 6 rows must expose Stability score separately');
assert.match(viewer,/title=\"Selected 6C score\"/,'Stage 6 rows must expose selected 6C score separately');
assert.match(viewer,/function score6Of\(id,role=mode6\)/,'6C score must come from the selected stored ranking run');
assert.match(viewer,/\.ra-pop'\)\.addEventListener\('click',e=>e\.stopPropagation\(\)\)/,'Region Analyzer menu controls must not trigger click-away closure');
assert.match(viewer,/initRegionColors\(manifest\);refresh\(\);render\(\);/,'manifest color table must be initialized before rendering regions');
assert.match(viewer,/color:regionColor\(id\)/,'rendered regions must carry their identity-derived color');
assert.doesNotMatch(viewer,/COLORS\[i%COLORS\.length\]/,'region colors must not depend on visible list position');
assert.match(viewer,/id=\"raEnabled\"/,'viewer menu must expose a Region Analyzer on/off control');
assert.match(viewer,/if\(!active\|\|!manifest/,'Region Analyzer off must suppress mask rendering without discarding state');
assert.match(viewer,/#raOverlay\{[^}]*background:transparent!important/,'Region Analyzer overlay must stay transparent over the base heatmap');
assert.doesNotMatch(viewer,/function mapping\(|mapping\(cur,src\)/,'viewer must not best-effort remap masks from semantic parameters');

console.log('PASS  Region Analyzer viewer is a static verifier/renderer with lightweight package identity binding');
